name: spotlight_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  video_player: ^2.10.1
  chewie: ^1.13.0
  shared_preferences: ^2.2.2
  # ğŸ‘‡ NUEVA DEPENDENCIA PARA TIPOGRAFÃA
  google_fonts: ^6.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#050B30"
  adaptive_icon_foreground: "assets/images/logo.png"